<?php

/**
 * @file
 * Primary module hooks for pet store friends module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
* Implements hook_theme().
*/
function pet_store_friends_theme($existing, $type, $theme, $path) {
  return [
    'friends-blog-list' => [
      'variables' => [
        'title' => [],
        'body' => [],
      ],
      'template' => 'friends-blog-list',
    ],
    'friends-blog-block' => [
      'variables' => [
        'title' => [],
        'body' => [],
      ],
      'template' => 'friends-blog-block',
      ]
  ];
}
